Add dummy libsdedrm module to satisfy ELF
error: vendor/qcom/common/vendor/display/5.15/Android.bp:448:1: "libsdmextension" depends on undefined module "libsdedrm".
Module "libsdmextension" is defined in namespace "vendor/qcom/common/vendor/display/5.15"

Change-Id: I36d10011b0d72d25e4d396443330bda05c2b7c43
Signed-off-by: Fazil Sheik <fazil.sheik96@gmail.com>
Signed-off-by: Richard Raya <rdxzv.dev@gmail.com>